### ISSUE TITLE
Info box displays extra table row with missing value for each vertex property

### ISSUE THREAD

**Issue by paul-k-civitas** [bricaud/graphexp#10]
The info box on the right-hand side displays an extra row for each vertex property when showing the properties of a vertex that has been clicked.
![screen shot 2018-03-01 at 9 07 38 am](https://user-images.githubusercontent.com/19958182/36853883-35c95ca4-1d35-11e8-853c-20823d02af38.png)

**Comment by bricaud** [comment]
Yes this is because each vertex property can have "VertexProperty" attached to them
http://tinkerpop.apache.org/docs/current/reference/#vertex-properties
These VertexProperties would be displayed in the Property column. However, in the graph example provided it is not used. I prefer to display an empty column rather than not displaying this info. But I agree it could be better. I did not find yet a simple way to do it.

**Comment by paul-k-civitas** [comment]
The issue I'm referring to is not the extra "Properties" column, but the extra _row_ for each property.
