### ISSUE TITLE
Initial placement of nodes

### ISSUE THREAD

**Issue by simbamford** [bricaud/graphexp#15]
Hi - I love what you've done here - it's very useful. 

For the project I'm working on I'm sometimes needing to drag the data around quite a bit after searching - i.e. the force-based simulation is an advantage in general but it would be good to initialise the node locations so that the layout after simulation is approximately related to some underlying features in my data. I could work with my gremlin DB easily enough so that each node had an x and y property. Then I could pull those out and add it to the data dictionary for each node - I'm seeing that d.x and d.y are worked with so presumably I could insert values for these if I could intervene at the right point. Here I'm struggling to work with your code. I'd be very grateful if you could tell me:

a) Is there any initialisation of node location implemented already?
b) Ideally, where would you intervene to copy a property of a node from the gremlin query to the graph visualisation data object?

Thanks a lot :)

**Comment by bricaud** [comment]
The nodes will move as soon as they appear on the graph due to the force layout. You would have to attach the property 'pinned' to them if you do not want them to move (just when you add them to the graph).
Sorry, I do not see a simple way to do what you suggest.
To answer your question b): all the node properties are copied from the DB to the visualization, see extract_infov3 or extract_infov2 in graphioGremlin.js, but an x and y property will be located in d.properties.x d.properties.y instead of d.x and d.y. You might want to change this.

**Comment by simbamford** [comment]
Thanks for your help :) Adding the following code to the loop in extract_infov3 did the trick:

if (key == 'x') {
	data_dic.fx = prop_dic['x']['0']['value'];
}
if (key == 'y') {
	data_dic.fy = prop_dic['y']['0']['value'];
}

Now, vertices which have an x and y property defined in the DB get fixed at that location, whereas other vertices remain free and subject to the force simulation. It's not clear to me why I needed to use the fx, fy properties rather than the x and y properties (?), anyway, this works.

**Comment by bricaud** [comment]
You can make a pull request and I will add it to Graphexp. It is an interesting feature to have.
