### ISSUE TITLE
AWS Neptune blank search fails

### ISSUE THREAD

**Issue by shanequint** [bricaud/graphexp#46]
I can get the "Get Graph Info" to pull back the vertex and edge information on a simple Neptune graph db I created using websockets, but when I do a blank "Search", it hangs and does not return.  I tried the following in the gremlin console and hangs also.  g.V().aggregate('node').outE().as('edge').inV().where(within('node')).select('edge').toList()

I also can't get REST to work at all, always gets timeout.  "Message: timeout, timeout"

**Comment by bricaud** [comment]
For the websocket version, It may be the same problem as in #44 . Neptune sends an 204 error instead of an empty list and it is not expected by Graphexp. It happens when you have no edge between the nodes that have been selected. In your case, it seems that you created a graph without any edge.
I will try to correct #44 in the following days. That may solve your problem.

**Comment by linllatamazon** [comment]
If you have a large amount of data in your Neptune cluster, it will take to transfer that over the network and into graphexp, try it with a smaller dataset.

**Comment by karlbaker02** [comment]
@shanequint Did you have any success with this? I'm also running into the same problem for a relatively small graph (500K nodes) and can confirm that the edges _do_ exist between those nodes.
