### ISSUE TITLE
Active project? Want to collaborate?

### ISSUE THREAD

**Issue by dwelch2344** [bricaud/graphexp#6]
Hey there. Is this still an active project? Have any interest in continued work / collaboration on it? Just got this running and love what I'm seeing so far. 

Just getting into Gremlin a bit deeper with AWS' Neptune and started playing with this. Neptune's got some limitations from traditional gremlin (such as no variables and single-statement queries only) but I've forked the project a bit and got it working. I think my changes will work for other Gremlin impl's, so figured I'd contribute upstream if you're interested. 

Either way, great work!

**Comment by bricaud** [comment]
Hi,
Yes, the project is active and I would be happy to have some help and collaboration with it!
I am open to any suggestions. If you want to contribute with a pull request please do. If you want to be more involved I can add you as a collaborator. I can even create a Github organization for the development of graphexp if someone is interested.
Thanks!

**Comment by bricaud** [comment]
I committed the changes done by [jwalton922](https://github.com/jwalton922) to allow the use of Graphexp with Neptune [https://github.com/bricaud/graphexp/pull/7](https://github.com/bricaud/graphexp/pull/7). Tests of the new update and improvements are welcome.

**Comment by jdbranham** [comment]
Cool project @bricaud !
I've "borrowed" GraphExp to use in a project I'm working on =]
https://github.com/savantly-net/spot

Once I understand more about D3 + Gremlin, I'd love to contribute back.
Most of what I know about it, has come from working on this integration!

**Comment by jdbranham** [comment]
@bricaud 
Would you accept a pull request that changes this to an Angular app?
Or would it be better for me to create a new repo?

**Comment by bricaud** [comment]
Thanks for your feedback @jdbranham !
I am open to any suggestion and having a better user interface would be great. But in the same time I would like to keep it simple:
* it is easier to understand for someone willing to learn how it works. You still have to understand D3.js Javascript and Gremlin. If we add angular it may be an additional thing to learn.
* its use is easy, you just have to open the html file in a browser. No need to install additional modules, npm or Node.js (even if Angular does not need Node.js)
*  its is simpler to maintain although this may not be a problem as I could receive help from contributors.

What I am thinking about now is that this repository could stay simple and be the core module for the visualization, a sort of backend for the visualization. I would still provide a minimal visualizer written in html for those interested in the simple version. And from it, people could build their own flavor of Graphexp with a better user interface, and perhaps more advanced options. So yes, you could create your own repo with an " angular graphexp". I would be pleased to add a link to it on my repo. And also I would be happy to make some changes in the files in order to have a code that is easier to import and handle in your version.
And if the Angular Graphexp becomes more popular than the simple one in the future, we could consider merging the contributions and creating a Github organization hosting it, where we would be contributors to this great project. Does it sound good to you?

**Comment by jdbranham** [comment]
Thanks @bricaud 
That sounds great!

I'll post more info here once I have something working.

**Comment by jdbranham** [comment]
I've started by extracting out the gremlins calls into a separate library.
There are zero dependencies!!

It's packaged up in multiple formats - a universal module file, an ES6 bundle, and a structured ES6 module, so it can be used in various scenarios.

It can be used directly in an html page - https://github.com/savantly-net/gremlin-js/blob/master/examples/index.html 
(so you can use in graphexp, if you'd like)

I dont have documentation yet, but I couldn't wait to share the progress.

**Comment by jdbranham** [comment]
fyi - the client was heavily inspired by 'gremlin-javascript' by @jbmusso 
https://github.com/jbmusso/gremlin-javascript

**Comment by jbmusso** [comment]
Just passing by. That's cool, keep up the good work.

**Comment by WalterInSH** [comment]
This project is awesome!

**Comment by jdbranham** [comment]
Thanks again @bricaud 
I've got an Angular component started - https://github.com/savantly-net/ngx-graphexp

I haven't got any documentation yet, but it is easily added to any existing Angular application.  
Some of the functionality from GraphExp is not available yet [like the property & color selections].

I've also started adding some 'edit' functionality, to be able to create new nodes, connect them, etc...

**Comment by Tameshiwari** [comment]
Hi jdbranham, sure will have a close look at your Angular App version. I stumbled on this as I started investing seriously in Azure Cosmos DB features including Graph API. I did manage to hook a very basic d3.js graph sample  to Azure Cosmos DB Graph API. I  use Small console app to feed the "juice" with a bit of gremlin syntax. So being able to connect your Angular to Azure Cosmos DB Graph API project would be an option some people would get crazy to get. Nice job!

**Comment by bricaud** [comment]
@jdbranham please add some documentation when you have time. I am a bit lost with your repos. If you have just a tutorial on how to intall your angular graphexp and a html page running it, that would be great. When I manage to run it, (and check it is working fine) I can add a link to it on the graphexp page. Thanks for your work!

**Comment by jdbranham** [comment]
@bricaud I added a demo app [here](https://github.com/savantly-net/ngx-graphexp/tree/master/examples/app)  

It's built for Angular 2+ so the structure is not like typical html/javascript.  
If you'll take a look at the latest [Angular IO](https://angular.io/) tutorials, you'll see.  A bit of a paradigm shift for client side development, using typescript that is transpiled to javascript.

**Comment by bricaud** [comment]
OK I understand now. You have rewritten the visualization. So if I make a modification or improvement on my code and you like it, you have to manually implement it on your side. And vice versa I can not add the new features you have made (like adding a node or an edge) easily. I should make graphexp more modular, so that people just write `<script>graphexp.js</script>` and everything is available, independently of the framework.

**Comment by jdbranham** [comment]
Yes. I've started modularization by abstracting the gremlin calls here -  

https://github.com/savantly-net/gremlin-js
