### ISSUE TITLE
Links to live demo

### ISSUE THREAD

**Issue by johnmckeever** [bricaud/graphexp#9]
I believe the README links to the live demo should be:
https://bricaud.github.io/graphexp/graphexp.html

**Comment by bricaud** [comment]
Thanks. I had this link before. The live demo was exploring the data from a gremlin server running on an AWS machine. But since github accept only https connections I had to setup a https server on AWS with a correct certificate (Github does not accept self-signed certificates). At the end, all this was too expensive just for a live demo, so I stopped it.
And you can not access a secure gremlin server that would run on your localhost because it uses a self-signed certificate.
I have removed the link to the live demo.
